name: module3_task1

on:
  push:
    branches: [main]
  schedule:
    - cron: "30 00 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "setup"
        run: cd module3_task1 && ./setup.sh

      - name: "make build"
        run: cd module3_task0 && make help
